FROM michaelwetter/ubuntu-1604_jmodelica_trunk

USER root
ENV HOME /home/root

RUN cd /root
WORKDIR /root

RUN apt-get update -y

RUN apt-get install -y python
RUN apt-get install -y curl

RUN pip install requests
RUN pip install boto3
RUN pip install minio
RUN pip install requests_toolbelt

RUN pip install pymongo


COPY . /root



ENV ROOT_DIR /usr/local
ENV JMODELICA_HOME $ROOT_DIR/JModelica
ENV PYTHONPATH $PYTHONPATH:$JMODELICA_HOME/Python:$JMODELICA_HOME/Python/pymodelica

CMD [ "python", "-u", "boptest.py" ]



