sudo: false
language: python
virtualenv:
  system_site_packages: false
services:
  - docker
matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOX_ENV=python DISTRIB="ubuntu" TOX_PYTHON_VERSION="py36" COVERAGE="true"
    - python: 3.6
      env: TOX_ENV=integration DISTRIB="ubuntu" TOX_PYTHON_VERSION="py36" COVERAGE="false"
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
before_script:
  - git config --global user.email "kyle.benne@nrel.gov"
  - git config --global user.name "kbenne"
script:
  - python setup.py develop
  - tox -e $TOX_ENV
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
