# Docker-compose setup for local development. This allows for a user
# to modify the Alfalfa worker code and run tests in the Docker
# container without needing to rebuild/restart Docker.
#
# Usage:
#   docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build

version: "3.4"
services:
  web: # main haystack application
    container_name: alfalfa_web
    build:
      # the purpose of context one level above dockerfile
      # is to utilize shared code, specifically in db
      dockerfile: alfalfa_web/Dockerfile
      context: .
      # The dev instance still needs works, so default to base for now
      target: dev
    image: ${WEB_REGISTRY_URI}:${VERSION_TAG}
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - "29043:29043"
    environment:
      - NODE_ENV=development
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - JOB_QUEUE_URL
      - MONGO_URL
      - MONGO_DB_NAME
      - S3_URL
      - S3_URL_EXTERNAL
      - REDIS_HOST
      - S3_BUCKET
      - REGION
    depends_on:
      - redis
      - mongo
      - goaws
      - worker
      - mc
    volumes:
      - ./alfalfa_web:/srv/alfalfa
      # create volumes for the build and node_modules so that
      # the resources are not copied back to the local host when
      # mounting.
      - /srv/alfalfa/build
      - /srv/alfalfa/node_modules
  worker:
    container_name: alfalfa_worker
    build:
      # the purpose of context one level above is to install the entire alfalfa package
      # and to copy the wait-for-it.sh and start_worker.sh files in the deploy directory
      dockerfile: alfalfa_worker/Dockerfile
      context: .
      target: dev
    image: ${WORKER_REGISTRY_URI}:${VERSION_TAG}
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - JOB_QUEUE_URL
      - MONGO_URL
      - MONGO_DB_NAME
      - LOGLEVEL=INFO
      - NODE_ENV
      - S3_URL
      - REDIS_HOST
      - S3_BUCKET
      - REGION
      - INFLUXDB_DB
      - INFLUXDB_HOST
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - HISTORIAN_ENABLE
    depends_on:
      - redis
      - mongo
      - goaws
      - mc
    volumes:
      - ./:/alfalfa
      # TODO: Add in worker fmu volume
      # TODO: Add in worker openstudio volume
