apiVersion: 1
datasources:
  - name: "influxAlfalfa" # name of the datasource
    access: "proxy" # make grafana perform the requests
    editable: true # whether it should be editable
    is_default: true # whether this should be the default DS
    type: influxdb # type of the data source
    url: http://${INFLUXDB_HOST}:8086 # url of the prom instance
    version: 1 # well, versioning
    database: $INFLUXDB_DB
    user: $INFLUXDB_ADMIN_USER
    password: $INFLUXDB_ADMIN_PASSWORD
