metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
output.elasticsearch:
  hosts: ["elasticsearch-master:9200"]
