name: CI

on:
  push:
  # Re-enable pull_request if we start receiving 3rd party contributions.
  # Otherwise, all pull_requests will also be push test and we are enforcing
  # that code must be up-to-date with parent in the PRs.
  #pull_request:

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          # use a newer version of poetry in this test, but
          # poetry in the dockerfile is a bit older because
          # of a urllib3 issue
          poetry-version: 1.3.1

      - name: Install poetry dependencies
        run: |
          poetry install

      - name: Runner Details
        run: |
          cat /etc/issue
          python --version

      - name: Start dependencies
        run: |
          printenv
          docker compose up -d mongo redis minio mc goaws

      - name: Run tests with pytest
        run: |
          poetry run pytest

  simulation-tests:
    name: Run simulation tests in worker
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # only need to start the worker which saves time here because
      # the webpack calling on the web container for .dev.yml can take some
      # time.
      - name: Build and run stack
        env:
          GIT_COMMIT: ${{ github.sha }}
        run: |
          printenv
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d worker mongo redis minio mc goaws

      - name: Wait another 30s for the containers to start
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"

      - name: Dump docker logs before tests
        uses: jwalton/gh-docker-logs@v1

      - name: Run job tests in Docker worker container
        run: |
          docker exec alfalfa_worker_1 bash -c "cd /alfalfa && pytest -m docker tests/jobs -o log_cli=true -o log_level=info"

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          # use a newer version of poetry in this test, but
          # poetry in the dockerfile is a bit older because
          # of a urllib3 issue
          poetry-version: 1.3.1

      - name: Build and run stack
        env:
          GIT_COMMIT: ${{ github.sha }}
        run: |
          printenv
          docker-compose up --build -d --scale worker=2

      - name: Wait for web server
        uses: nev7n/wait_for_response@v1
        with:
          url: "http://localhost/"
          responseCode: 200
          timeout: 120000
          interval: 500

      - name: Wait another 30s
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"

      - name: Dump docker logs before tests
        uses: jwalton/gh-docker-logs@v1

      - name: Run tests with pytest
        run: |
          poetry install
          poetry run pytest --timeout=600 -m "integration"

      - name: Run worker scale tests with pytest
        run: |
          poetry install
          poetry run pytest -m "scale"

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

  integration-tests-historian:
    name: Run integration tests with historian
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          # use a newer version of poetry in this test, but
          # poetry in the dockerfile is a bit older because
          # of a urllib3 issue
          poetry-version: 1.3.1

      - name: Build and run stack
        env:
          GIT_COMMIT: ${{ github.sha }}
        run: |
          export HISTORIAN_ENABLE=true
          printenv
          docker-compose -f docker-compose.yml -f docker-compose.historian.yml up --build -d --scale worker=2

      - name: Wait for web server
        uses: nev7n/wait_for_response@v1
        with:
          url: "http://localhost/"
          responseCode: 200
          timeout: 120000
          interval: 500

      - name: Wait another 30s
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"

      - name: Dump docker logs before tests
        uses: jwalton/gh-docker-logs@v1

      - name: Run tests with pytest
        run: |
          poetry install
          poetry run pytest --timeout=600 -m "integration"

      - name: Run worker scale tests with pytest
        run: |
          poetry install
          poetry run pytest -m "scale"

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

  publish:
    if: |
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      # Only if all other jobs pass.
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          running-workflow-name: "publish" #this job shouldn't wait for itself
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20 # seconds

      - name: Checkout code
        uses: actions/checkout@v2

      # Install only toml, which is used to extract version.
      # We don't do anything else with Python in this job.
      - name: Install toml
        run: python -m pip install toml

      - name: Build & Publish Images
        shell: bash
        run: ./.github/workflows/publish_to_docker.sh
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
